### ISSUE TITLE
The size of tensor a (1852) must match the size of tensor b (463) at non-singleton dimension 2

### ISSUE THREAD

**Issue by srijoniC** [motazalfarraj/Semi-supervised-Learning-for-Acoustic-Impedance-Inversion#1]
I'm training it on a different data with a sample size of 463 and trace of 5771. Its showing Input size not matching error.

UserWarning: Using a target size (torch.Size([20, 1, 463])) that is different to the input size (torch.Size([20, 1, 1852])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.

Please Help.

**Comment by motazalfarraj** [comment]
For some reason, I did not receive an email notification about this error. Apologies ! 

In your data, the single trace at 5771 samples? or 463?
